default:
  image: archlinux:latest
  before_script:
    - pacman -Syyu --noconfirm
    - pacman -S --noconfirm -y cmake clang

stages:
  - check-cpp-formatting

cache:
  policy: pull-push

check-cpp-formatting:
  stage: check-cpp-formatting
  script:
    - cd cpp
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build . --target clang-format-check-formatting
    - cd ..
    - rm -rf build
