default:
  image: archlinux:latest
  before_script:
    - pacman -Syyu --noconfirm
    - pacman -S --noconfirm -y cmake clang jdk-openjdk gradle
    - archlinux-java set java-14-openjdk
    - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - check-cpp-formatting

cache:
  policy: pull-push

check-cpp-formatting:
  stage: check-cpp-formatting
  script:
    - cd cpp
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build . --target clang-format-check-formatting
    - cd ..
    - rm -rf build
