default:
  image: openjdk:latest

stages:
  - check-cpp-formatting

cache:
  policy: pull-push

check-cpp-formatting:
  stage: check-cpp-formatting
  script:
    - cd cpp
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build . --target clang-format-check-formatting
    - cd ..
    - rm -rf build
