default:
  image: ubuntu:latest
  before_script:
    - apt-get update
    - apt-get install -y cmake clang-format openjdk
    - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - check-cpp-formatting

cache:
  policy: pull-push

check-cpp-formatting:
  stage: check-cpp-formatting
  script:
    - cd cpp
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build . --target clang-format-check-formatting
    - cd ..
    - rm -rf build
