variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  policy: pull-push

stages:
  - check-cpp-formatting

default:
  image: archlinux:latest
  before_script:
    - pacman -Syyu --noconfirm
    - pacman -S --noconfirm -y make cmake clang gcc opencv unzip curl zip tar git
    - ./vcpkg/bootstrap-vcpkg.sh -disableMetrics
    - ls -al vcpkg
    - ./vcpkg/vcpkg install pistache
    - ./vcpkg/vcpkg install rapidjson
    - ./vcpkg/vcpkg install nlohmann-json
    - ./vcpkg/vcpkg install gtest

check-cpp-formatting:
  stage: check-cpp-formatting
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_TOOLCHAIN_FILE=$(realpath vcpkg/scripts/buildsystems/vcpkg.cmake) ..
    - cmake --build . --target clang-format-check-formatting
    - rm -rf build
