default:
  image: openjdk:latest

stages:
  - compile
  - test

before_script:
  - export GRADLE_USER_HOME=./.gradle

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - .gradle/caches
    - .gradle/wrapper
  policy: pull

compile:
  stage: compile
  script:
    - ./gradlew assemble
  cache:
    policy: push

test:
  stage: test
  script:
    - ./gradlew check
