variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  policy: pull-push

stages:
  - check-cpp-formatting
  - compile
  - test

default:
  image: archlinux:latest
  before_script:
    - pacman -Syyu --noconfirm
    - pacman -S --noconfirm -y make cmake clang gcc opencv unzip zip git qt5-base vtk
    - ./vcpkg/bootstrap-vcpkg.sh -disableMetrics
    - ./vcpkg/vcpkg install pistache
    - ./vcpkg/vcpkg install rapidjson
    - ./vcpkg/vcpkg install nlohmann-json
    - ./vcpkg/vcpkg install gtest

check-cpp-formatting:
  stage: check-cpp-formatting
  before_script:
    - ''
  script:
    - ./check-formatting

compile:
  stage: compile
  script:
    - ./compile

test:
  stage: test
  script:
    - ./test
