variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  policy: pull-push

stages:
  - check-cpp-formatting

default:
  image: archlinux:latest
  before_script:
    - pacman -Syyu --noconfirm
    - pacman -S --noconfirm -y make cmake clang gcc opencv unzip zip git
    - ./vcpkg/bootstrap-vcpkg.sh -disableMetrics
    - ./vcpkg/vcpkg install pistache
    - ./vcpkg/vcpkg install rapidjson
    - ./vcpkg/vcpkg install nlohmann-json
    - ./vcpkg/vcpkg install gtest

check-cpp-formatting:
  stage: check-cpp-formatting
  script:
    - ./check-formatting
